### ISSUE TITLE
Deliver callbacks?

### ISSUE THREAD

**Issue by princemaple** [thoughtbot/bamboo#126]
@paulcsmith what do you think about callbacks for `deliver_later` success/failure?

Looking at the code, I can see how to handle `deliver_now`, with a `try`
But for `deliver_later`, there doesn't seem to be a way to handle success/failure.

One thing that can come close is to implement a new strategy that does generic handling of errors.
However, if we want business logic specific handling of success/error, there probably need to be callbacks / other smarter stuff.

**Comment by paulcsmith** [comment]
I think this is an interesting idea, but I'm not sure how to best implement this. Could you give some example use cases for this feature?

**Comment by princemaple** [comment]
How do you handle errors right now? For `deliver_later`.

**Comment by paulcsmith** [comment]
@princemaple I don't handle errors right now for `deliver_later`. If I need to handle the error and display to the user then I would use `deliver_now` otherwise it gets way to tricky. So if you need some kind of immediate response I would use deliver_now and handle errors returned by it. If you want to handle errors from `deliver_later` then I would create a new Bamboo.Strategy for sending that handles the error in there.

I'm going to close this for now, but feel free to continue the conversation here. I may have misunderstood your question, if that's the case, LMK and I'll try to help
