### ISSUE TITLE
Add Josh's excellent Bamboo episode from DailyDrip.com to README

### ISSUE THREAD

**Issue by paulcsmith** [thoughtbot/bamboo#152]
It's free and awesome: https://www.dailydrip.com/topics/elixir/drips/bamboo-email

**Comment by Homerade** [comment]
Link is dead. Is this the video that was on there: https://www.youtube.com/watch?v=tHfGXnrvksQ

**Comment by germsvel** [comment]
Thanks for pointing that out @Homerade. I don't know which video daily drip had, but since the link is dead I replaced it with links to the ElixirCasts video you shared (I followed it to the ElixirCasts website): 

https://elixircasts.io/sending-email-with-bamboo-part-1 and https://elixircasts.io/sending-email-with-bamboo-part-2
