### ISSUE TITLE
When Elixir 1.3 is required, use String.myers_difference to show diffs for emails

### ISSUE THREAD

**Issue by paulcsmith** [thoughtbot/bamboo#155]
Sometimes emails can become quite large and it's hard to tell what is different. We could use http://elixir-lang.org/docs/master/elixir/String.html#myers_difference/2 to show the differences between emails. This will make it easier to spot typos and things like that.

**Comment by germsvel** [comment]
@paulcsmith I don't imagine you remember this, but I'm wondering if this still makes sense to work on? Looking through [Bamboo.Test](https://github.com/thoughtbot/bamboo/blob/master/lib/bamboo/test.ex), I don't see any obvious places where we compare emails as strings (to use `String.myers_difference/2`).  

It seems like the majority of the `flunk_x` functions that show errors were created after this issue was opened, and they show pretty good messages. I imagine we can still improve on those messages, but not with `String.myers_difference/2`. You okay if I close this issue?

**Comment by germsvel** [comment]
I'll go ahead and close this issues since it doesn't seem like something we need anymore. If anyone thinks otherwise, please let me know, and I'd happily reopen it.
