### ISSUE TITLE
Add message_id to Email struct definition

### ISSUE THREAD

**Issue by tdcain89** [thoughtbot/bamboo#161]
This may be a need unique to my situation, but it would help to be able to set a Message-ID prior to delivering an email so that the value can be saved to a database table and can be referenced later. Something similar is available in the [Ruby Tmail Library](https://github.com/mikel/tmail/blob/eb43e766cbad6125508f95223b8c0bc89cfdcff1/lib/tmail/interface.rb#L573) .

**Comment by paulcsmith** [comment]
Can you give an example use case for this? For now you can do something similar to what's done in `Bamboo.SentEmail` https://github.com/thoughtbot/bamboo/blob/master/lib/bamboo/sent_email.ex#L115

You can use the `private` key of the email to put an id of your choosing. You could this for all your emails before sending them in a `base_email` function in your mailer

```elixir
defp base_email do
  new_email
  |> from("default@myapp.com")
  |> put_rand_id
end

defp put_rand_id(email) do
  # Use code from Bamboo.SentEmail
end
```

Does that help?

**Comment by tdcain89** [comment]
Use case: 

(Mandrill, MailGun, etc.) return a message id in their response. I'd like to pump that value into ```%Bamboo.Email{message_id: "___"}``` when available and then save the contents of the struct to a table. If I identify that an email has bounced, I can take the ID of that bounced email and quickly lookup the details of that email in the database, reconstruct it and attempt to resend.

Does that make sense?

**Comment by paulcsmith** [comment]
Ah yes that makes sense. I think that is something that would be adapter specific, but I can see how that would be useful. I think this is a good idea, but I’m not sure when I can get to it. I’ll do what I can though :)

**Comment by StevenXL** [comment]
Hello. I'm looking for an Elixir project to regularly contribute to in order to become a better Elixir developer. I thought I would contribute a PR for this issue as it seems @paulcsmith has decided it's a good idea to implement it.

However, I don't see how this feature is possible in a non-blocking way, and it would require a change in the API of [`Bamboo.Mailer.deliver_now/3`](https://github.com/thoughtbot/bamboo/blob/master/lib/bamboo/mailer.ex#L116).

## Current Functionality

The `id` field that we'd hope to save in the `Bamboo.Email` struct would not be available until *after* the request is sent to Mandrill, in the [response](https://mandrillapp.com/api/docs/messages.JSON.html#method=send) from Mandrill.

So, in order to get the `id` from Mandrill, we'd have to send the request via our mailer's `deliver_now/1` or `deliver_later/1` functions. 

Our mailer module eventually calls `Bamboo.Mailer.deliver_now/3` or `Bamboo.Mailer.deliver_later/3`, and these functions eventually call the functions in our adapter. 

However, in both `Bamboo.Mailer.deliver_now/3` and `Bamboo.Mailer.deliver_later/3`, we don't care about the return values of the adapter's functions, as we always return the email passed into `Bamboo.Mailer.deliver_now/3` / `Bamboo.Mailer.deliver_later/3`. 

## Implementation 

In order to allow a `Bamboo.Email` struct, with the `id` field populated, to be returned by a call to `Mailer.deliver_now/1`, we'd have to start caring about the return values of our adapter. This means changing `Bamboo.Mailer.deliver_now/3` to this:

```
  def deliver_now(adapter, email, config) do
    email = email |> validate_and_normalize

    if email.to == [] && email.cc == [] && email.bcc == [] do
      debug_unsent(email)
      email
    else
      debug_sent(email, adapter)
      adapter.deliver(email, config)
    end
```

At this point, we'd have to require that `adapter.deliver/2` always returns an email so that we don't break the API of `Bamboo.Mailer.deliver_now/3`. This means that `adapter.deliver/2` has to change. In the case of the Mailgun / Mandrill adapter, it would return to us a `Bamboo.Email` struct  with the `id` in it somewhere if successful. But what about errors? 

@paulcsmith let me know how you'd like to proceed with this. I'm happy to help, but would probably need your thoughts on architectural decisions

**Comment by paulcsmith** [comment]
@StevenXL Those are some excellent points. It seems like this could be quite tricky. I'll have to think about this some more. I'll probably have time on Friday to respond with some ideas!

**Comment by StevenXL** [comment]
@paulcsmith No problem. Looking forward to sharing ideas on Friday.

**Comment by asummers** [comment]
Hello, just curious if there's been any movement on this guy. This would be useful for our needs as well, as the ID returned from scheduling a Mandrill email for later using the header X-MC-SendAt header allows the scheduled message to be canceled using this ID. One can imagine the usefulness of being able to cancel "day before" emails on events that get canceled in some sort of ticket software, for example.

**Comment by bnns** [comment]
Here's my attempt (#308). It seemed easier to just expose the entire response in `%Email{response: response}` rather than deal with decoding JSON to find the id. This also allows handling different error cases. You can now do something like the following (works with `MandrillAdapter`)

```elixir
defmodule MyApp.Mailer do
  use Bamboo.Mailer, otp_app: :my_app

  def send_email(email: email) do
    email_id =
      email
      |> deliver_now
      |> Map.fetch!(:response)
      |> Map.fetch!(:body)
      |> Poison.decode!
      |> hd
      |> Map.fetch!("_id")

    {:ok, email_id}
  end
end
```

**Comment by coryt** [comment]
Any update on this issue? I also need this functionality to be able to track events from the SendGrid webhook. I can work around this by using CustomArgs but being able to track the raw message-id would be preferable. 

If needed I can help out with this issue.

**Comment by StevenXL** [comment]
@coryt Happy to pair with you on this. I haven't used Elixir in a long time, so would be nice to pair with an experienced person on it. If that sounds like something you'd be interested in, please let me know how to contact you and we can work out the logistics.

**Comment by jeffmiller00** [comment]
We would also like this issue -- we can also help pair / develop. What's outstanding in order to get this merged?

**Comment by maymillerricci** [comment]
Sorry for the delay! I opened #452 which includes the response from the adapter's `deliver` call as an additional key in the `Email` struct returned from `deliver_now`, similar to #308 but not changing the type of what's returned. This should include the desired data from the various adapters. Let me know if you have any thoughts and whether you think it might resolves this!

**Comment by germsvel** [comment]
It seems that this issue was resolved by https://github.com/thoughtbot/bamboo/pull/466 returning the `{email, response}` if `response: true` is passed to `deliver_now/2`. I'll go ahead and close it, but if people feel like this hasn't been resolved, please let me know! Happy to reopen the issue.
