### ISSUE TITLE
Content Display Problem in Apple Mail

### ISSUE THREAD

**Issue by bigcurl** [thoughtbot/bamboo#193]
The following mail does not display content in Apple Mail. The content is displayed on Googles Gmail Web site though.

    new_email(
      to: "test@gmail.com",
      from: "test@example.com",
      subject: "Testing Bamboo",
      html_body: "<h1>Hey</h1><p>Check out this email or else.</p>",
      text_body: "# Hey\n\nCheck out this email or else."

![bildschirmfoto 2016-07-03 um 23 16 52](https://cloud.githubusercontent.com/assets/34068/16547605/572ef758-4174-11e6-84a8-cd4703308d45.png)

**Comment by paulcsmith** [comment]
@bigcurl I'm not sure this is a problem with bamboo or not. Sounds like it might be a problem with the email itself. Can you paste the full code including which adapter is being used?

**Comment by bigcurl** [comment]
You'll find a small project here https://github.com/bigcurl/bamboo_gmail_test that I used to send the mail. Files of interest are 
* `config/config.exs` where `Bamboo.SMTPAdapter` is defined.
* `lib/send_gmail.ex` where the mail creation code is defined.

Mail is send by running `iex` and `SendGmail.Email.welcome_email |> SendGmail.Mailer.deliver_later`

**Comment by bigcurl** [comment]
@paulcsmith Is the code sufficient to reproduce the problem?

**Comment by paulcsmith** [comment]
@bigcurl Yes that helps a lot. I think this is a problem with bamboo_smtp or gen_smtp (which bamboo_smtp relies on). I would open an issue on [bamboo_smtp](https://github.com/fewlinesco/bamboo_smtp) since they may be able to help more. I don't use the SMTP version so I haven't had much experience with it.

If you open an issue there and there is no response, please comment here and I can try to take a look!
