### ISSUE TITLE
ESpec helpers

### ISSUE THREAD

**Issue by facto** [thoughtbot/bamboo#194]
Is there any interest in this? If so, I'll contribute a module (`Bamboo.Spec`, perhaps).

**Comment by paulcsmith** [comment]
@facto I hadn't heard of ESpec before. I think this is a great idea, but since I don't use it and no one else at thoughtbot uses it, I don't think we would be the best maintainers for this.

What do you think about making a `bamboo_espec` library? I'd be happy to put a link in the README. That way people can find it, and it will be better maintained by people that actually use ESpec. Thoughts?

**Comment by facto** [comment]
Definitely! I'll send a PR with a link in the README when it's ready. Cheers.
