### ISSUE TITLE
Need a common Exception type

### ISSUE THREAD

**Issue by geofflane** [thoughtbot/bamboo#196]
Adding this for discussion mostly.

Each of the individual Adapters defines its own Exception module/struct. That means if you want to catch the exceptions thrown by `deliver_now` you have to use one specific to the Adapter that's currently configured for use. That makes `Bamboo.Mailer` a leaky abstraction since you have to change the error handling if you change the adapter.

e.g.:

```
try do
  Email.welcome_email |> Mailer.deliver_now
rescue
  e in Bamboo.MailgunAdapter.ApiError ->
    # ... record the error
end
```

Having a common `Bamboo.Mailer.Error` that the adapters could use would solve that problem. But, maybe it would be better to have a more Elixir style "maybe monad" return using `{:ok, response}` and `{:error, response}` instead of raising an exception?

**Comment by jbernardo95** [comment]
@geofflane I believe that the tuple alternative is the most elixirish like.

As I am learning elixir, I would be happy to open a PR addressing this, @paulcsmith can I get your input on this ? Would this be something for the 1.0 milestone (or even 2.0) ?

**Comment by jbernardo95** [comment]
@paulcsmith Up

**Comment by paulcsmith** [comment]
I think a common exception type is a great idea. I don't think that it should return `{:ok, response}` or `{:error, response}` because it's far too easy to forget to match on `{:ok, _}` and get unhanded and unnoticed exceptions.

**Comment by jbernardo95** [comment]
Makes sense, I will do a draft on this and make a PR after to get your input.

**Comment by paulcsmith** [comment]
Awesome. Thank you so much @jbernardo95!

**Comment by jbernardo95** [comment]
@paulcsmith Here it is ^

**Comment by waiting-for-dev** [comment]
Really nice and needed addition!! :+1: 

However, I think it should have been better to go with the `{:error, _}` way. It is equally easy to forget to match the `{:error, _}` result that to rescue a possible exception. And, in both cases, an error would be logged. (In fact, I think it is easier to forget a rescue, because if you are using type specification you see the `:error` there).

In elixir and other functional languages, this is not too idiomatic neither recommended. As it is said in the [guides](https://elixir-lang.org/getting-started/try-catch-and-rescue.html):

> In Elixir, we avoid using try/rescue because we don’t use errors for control flow. We take errors literally: they are reserved for unexpected and/or exceptional situations. In case you actually need flow control constructs, throws should be used.

For example, in elixir reading a file with `File.read` returns an `:ok`/`:error`, because both are the natural outcomes of trying to open a file: you succeed or you don't succeed. I think it is the same with sending an email. At the most, it could exist a counterpart `deliver!` which should be used when a failure sending an email is considered excepcional (just like `File.read!`).
