### ISSUE TITLE
Email Preview to support Mandrill templates

### ISSUE THREAD

**Issue by smdern** [thoughtbot/bamboo#209]
RIght now if you hit the email preview plug you can see an email was sent, but if using Mandrill templates then the content is empty (since text + html wasn't used).

 If we could preview how Mandrill rendered the template that would be awesome, but could be a considerable effort. I'd be happy w/ just seeing the json that was sent to Mandrill.

**Comment by paulcsmith** [comment]
I'm not totally sure if I'll make this a priority, but I do think this is an interesting idea. I'm not sure of the best way to handle this. Maybe when viewing the email we could check if `html_body` and `text_body` are empty. If that's the case just show the full email struct so that you can inspect what was sent? I think that could be helpful even if you aren't using Mandrill templates.

For now though, you can do `Bamboo.SentEmail.all |> List.first`from `iex` to get the newest email and see what was sent. Not *quite* as convenient, but at least it's possible.

**Comment by tlvenn** [comment]
Why not use the '/templates/render.json' API endpoint to get the rendered template ?

**Comment by lancejjohnson** [comment]
Closing in light of the recommended solutions. Please reopen if this is still an issue.
