### ISSUE TITLE
SendGridAdapter not available

### ISSUE THREAD

**Issue by dvanderbeek** [thoughtbot/bamboo#278]
I'm getting an Internal Server Error when attempting to send via SendGrid on Heroku. Logs show this message:

```
** (UndefinedFunctionError) function Bamboo.SendGridAdapter.handle_config/1 is undefined (module Bamboo.SendGridAdapter is not available)
```

It does not error out when I try switching to Mailgun, but I would like to use SendGrid if possible.

**Comment by paulcsmith** [comment]
@dvanderbeek Could you try using `Bamboo.SendgridAdapter` (note the lowercase g). The docs here on master are for the latest version of Bamboo. For the docs for the latest hex version, see these: https://hexdocs.pm/bamboo/0.8.0/readme.html

In there you will see that the adapter is spelled with a lower case `g`

LMK if that works for you :)

**Comment by dvanderbeek** [comment]
@paulcsmith Yep, I just caught that and was about to update the issue here. Thanks for the quick reply!

**Comment by paulcsmith** [comment]
You're welcome! I'm glad it's working now :)

**Comment by antoniosb** [comment]
I'm getting this while trying to use `1.0.0-rc.1` with sendgrid:

```elixir
[error] beam/beam_load.c(1412): Error loading module 'Elixir.Bamboo.SendgridAdapter':
  module name in object code is Elixir.Bamboo.SendGridAdapter
```

**Comment by happysalada** [comment]
this wrong spelling is still in the readme on master, people might still end up here.

**Comment by dsignr** [comment]
^I ended up here because the readme has it wrong.

**Comment by robacarp** [comment]
A little update. If your reading this, the spelling needs to be SendGrid now.

Upgrading our app from Bamboo ~0.8 to ~> 1.1.0, the spellinG changed from Sendgrid to SendGrid. 

We hit a similar error to the title of this issue and then dismissed it when "we had it right" because of the comment history (oops! 🤦‍♂️). At any rate, [as of a while ago](https://github.com/thoughtbot/bamboo/commit/6b582f80781f0072bd4051084a3286991bfde2d0) the correct spelling is [SendGrid](https://github.com/thoughtbot/bamboo/blob/master/lib/bamboo/adapters/send_grid_adapter.ex#L1)

**Comment by mackshkatz** [comment]
@robacarp *you're :) Love you :)

**Comment by kelraf** [comment]
Thanks, @paulcsmith your solution saved my day.
