### ISSUE TITLE
Fix dead link in the Sent Email Viewer section of the README

### ISSUE THREAD

**Issue by jessica-jordan** [thoughtbot/bamboo#295]
*Current*
The link for the email viewer plug setup instructions found in this README section:
https://github.com/thoughtbot/bamboo#viewing-sent-emails
is pointing to an outdated version of the bamboo docs.

*Expected*
The link points to the new version at https://hexdocs.pm/bamboo/Bamboo.EmailPreviewPlug.html instead.

**Comment by paulcsmith** [comment]
Explanation for closure here: https://github.com/thoughtbot/bamboo/pull/296#issuecomment-306884083 Sorry for the confusion!

**Comment by jessica-jordan** [comment]
@paulcsmith Thanks for the update! Unfortunately, the link in the readme is still leading to a 404. Shouldn't this issue stay open then and the PR be improved to link to the properly named module in the hexdocs instead? Please let me know if the described link works for you in the current Readme or if this should be improved otherwise

**Comment by paulcsmith** [comment]
Sorry I did not explain that well, if you go to the currently published docs on hex https://hexdocs.pm/bamboo/readme.html the link is to the correct module. The version here on master is for the beta, so the links won't necessarily work because it has not been released publicly yet. That's why there is a not at the beginning of the README directing people to check the docs on hex. Maybe I need to make that more prominent or explain it better. Do you have any ideas for how that could be clarified so it makes more sense?

**Comment by paulcsmith** [comment]
Also I realize this can be a bit confusing. I think what I'm going to do in the future is keep a separate README-latest.md or something and move it to README.md once the docs have been published. That way people won't get confused. In the meantime though I'll keep it since the new version is getting close to release :D
