### ISSUE TITLE
Add callback to deliver_later/1

### ISSUE THREAD

**Issue by shhavel** [thoughtbot/bamboo#346]
Add callback function argument to `deliver_later/1` which is executed on successful email delivery:

```elixir
Email.welcome_email
|> Mailer.deliver_later(fn -> callback() end)
```

This for example can be used to build a reliable messaging system that stores emails in the database, sends email and mark it sent after successful delivery. All failed message can be resent.

**Comment by stefmona** [comment]
Have you try to use strategies:
https://github.com/thoughtbot/bamboo/blob/e8a80137f5ef221f7f98514b56b338f56c994f65/lib/bamboo/strategies/immediate_delivery_strategy.ex

**Comment by germsvel** [comment]
I'm going to close this because of inactivity. I think using a custom deliver later strategy makes sense in this case. But if there was a way we could create a generic callback mechanism, it could be interesting to introduce that. But I'd rather not introduce it unless we have a real use case for it. So, I'll close this for now. If others feel like it should be reopened, I'd be glad to do so. Or we can open a new issue.
