### ISSUE TITLE
extract Mailer as a standalone umbrella app and use Bamboo.SentEmailViewerPlug in Web app

### ISSUE THREAD

**Issue by mpugach** [thoughtbot/bamboo#439]
Hello

I would like to extract the mailer to a separate umbrella app

So it would be:
- main_app
- mailer
- web (phoenix)
- ...

But I stuck trying to expose `Bamboo.SentEmailViewerPlug` to `web`

Is there an easy way to see the emails in development for this kind of setup?

**Comment by sb8244** [comment]
@mpugach in an umbrella app, are the different apps fully isolated? If so, you would need to cross the isolation boundary explicitly. 

One option could be for your mailer app to expose the development viewer on a dedicated port.

**Comment by mpugach** [comment]
@sb8244 do you mean my `mailer` app includes a web layer, so I have two web apps in my umbrella?

**Comment by sb8244** [comment]
That is how I would handle it, mainly because it's Dev only (can be configured at compile time) and avoids sending data across the boundary

**Comment by germsvel** [comment]
I haven't tried to separate the mailer in a separate umbrella app, so unfortunately cannot leave a helpful comment here. 

I know it's been a while since this issue was opened, and it seems like not many others have thoughts on this. I wonder if the question would get more traction in the [Elixir slack](https://elixir-slackin.herokuapp.com/) or [Elixir forum](https://elixirforum.com/)? 

For now, I think I will close this. If others have thoughts and want to reopen this. Please let me know. I'd be happy to do so!
