### ISSUE TITLE
Next Bamboo release? 

### ISSUE THREAD

**Issue by talum** [thoughtbot/bamboo#448]
Hi! 

Are there any plans to release the changes since August 15 on Hex? We would love to use the SendGrid dynamic templates functionality added in #426. (I see we can pull from master, but we'd appreciate the stability of a release.)

Thanks for your work on this 😄 .

**Comment by cdfuller** [comment]
Looks like the main contributor, Paul, left thoughtbot for a new job.

@paulcsmith would you happen to know if anybody took over this project?

**Comment by paulcsmith** [comment]
Thank you for pinging me! @germsvel could you post this internally to see if someone is interested in taking over?

I'd be happy to help with the transition. I think the main thing to do is release a new version. 

The main support burden are the different adapters. I would consider extracting the individual adapters so that they can be maintained separately, preferably by someone in the community that uses the service (SendGrid, Mailgun, etc.). The core of Bamboo is pretty solid so this would reduce. a lot of the maintenance burden

**Comment by germsvel** [comment]
@paulcsmith thanks for pinging me. I posted this internally to see if someone is interested. I have considered taking over myself, but I didn't want to commit and risk doing a bad job by spreading myself too thin. But I can definitely help with another deploy and maybe with the extracting

**Comment by germsvel** [comment]
Hi @talum, I just released [v1.2.0](https://github.com/thoughtbot/bamboo/blob/master/CHANGELOG.md#120---2019-01-30) of Bamboo. Thanks for opening this issue and bringing this to our attention!

**Comment by talum** [comment]
Thank you so much! Very exciting.
