### ISSUE TITLE
Allow configuration of receive timeout for assert_*, and refute_* functions

### ISSUE THREAD

**Issue by validere-ben** [thoughtbot/bamboo#506]
# Context
We're currently running into issues with intermittent test failures in certain environments due to the hardcoded 100ms receive timeout on these test assertions. 

Judging from https://github.com/thoughtbot/bamboo/pull/228 100ms being hardcoded seems quite arbitrary?

# Suggestions
Having a `:timeout` opt be added to these functions or adding `/2` variants allowing a timeout specification would be a welcome extension. 

There is also the existing `refute_timeout` configuration option which seems to only be used with `assert_no_emails_delivered/0` currently (should `refute_email_delivered_with/1` be using this as well?). Following this existing convention, an `assert_timeout` 'global' configuration option might be more suitable?

I'd be happy to cut a PR with the changes depending on the approach/solution preferred for this.

**Comment by germsvel** [comment]
Hi @validere-ben. Thank you for opening up this issue, and thanks for the patience! I think it'd be a great idea to make that timeout configurable by passing a `timeout` option. We can just keep 100ms as the default. I know it's been a while since you opened this issue, but if you're interested, I'd review a PR for this. Otherwise, thanks for the idea. Maybe someone else will come along and be interested in taking this.
