### ISSUE TITLE
No explanation of *where* to configure *real* email and password information for sending

### ISSUE THREAD

**Issue by roostercrab** [thoughtbot/bamboo#508]
I have read all the documentation that I can find and watched all the screencasts and they all stop at how to TEST sending an email but none of them say where to configure your ACTUAL email address and password!

**Comment by parkerduckworth** [comment]
Which Adaptor are you using?

**Comment by roostercrab** [comment]
I'll be honest, I have no idea which one to use. I have tried SMTPAdapter because I have a Gmail account that I can use, but that's as far as I've gotten.

**Comment by parkerduckworth** [comment]
I actually set up a service using the `SMTPAdapter` for Gmail this week.

You have to add `{:bamboo_smtp, "~> 2.1.0"}` as a separate dependency in your `mix.exs` file, then add `:bamboo_smtp` to the list inside your `application/0` function in `mix.exs` as well.

Then in the config file for whatever env you're developing in , add this code snippet, where you can insert your username/password for gmail.
```elixir
config :my_app, MyApp.Mailer,
  adapter: Bamboo.SMTPAdapter,
  server: "smtp.domain",
  hostname: "your.domain",
  port: 1025,
  username: "your.name@your.domain", # or {:system, "SMTP_USERNAME"}
  password: "pa55word", # or {:system, "SMTP_PASSWORD"}
  tls: :if_available, # can be `:always` or `:never`
  allowed_tls_versions: [:"tlsv1", :"tlsv1.1", :"tlsv1.2"], # or {:system, "ALLOWED_TLS_VERSIONS"} w/ comma seprated values (e.g. "tlsv1.1,tlsv1.2")
  ssl: false, # can be `true`
  retries: 1,
  no_mx_lookups: false, # can be `true`
  auth: :if_available # can be `:always`. If your smtp relay requires authentication set it to `:always`.
```

Google's SMTP server is called `smtp.gmail.com` and listens on port `587`


---


The above snippet is found [here in the `bamboo_smtp` docs](https://hexdocs.pm/bamboo_smtp/Bamboo.SMTPAdapter.html).

*One caveat* - you have to [enable less secure apps (LSA's)](https://support.google.com/accounts/answer/6010255?hl=en) in your Gmail settings since the `SMTPAdapter` does not use OAuth for authentication.


---


### A word of caution 
According to [this post on Google's GSuite Updates Blog](https://gsuiteupdates.googleblog.com/2019/12/less-secure-apps-oauth-google-username-password-incorrect.html), in about a year you will no longer be able to enable LSA's to interact with Google services.  

I have brought this up in issue #507.  I am considering writing an `OAuthAdapter` or `GMailAdapter` over the holidays to address this, but am waiting to hear back from the bamboo community about their thoughts on this.

For now, as long as your enable LSA's in your gmail account, you can still use bamboo with Gmail.

**Comment by roostercrab** [comment]
Ok cool, I had gotten that exact setup and even went so far as to get an API key from my GSuites account. It looks like I won't need the API key, but I didn't know about the Less Secure Apps part of it.

Sorry for the frustrated wording in the heading, I am recovering from Stack Overflow's community still it seems...If you are able to write a more future proof version of this to connect to Gmail then I will be one of the first to use it.
