### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by mmendez512** [thoughtbot/bamboo#515]
There are over 10 open PRs and over 40 open issues which begs the question: Has this project been abandoned? 

If that's the case, I suggest you ask the community if another person(s) can take this over.

**Comment by joshchernoff** [comment]
I was at one point about a year ago seeing some activity though I'm not sure if the same people are currently involved anymore.

**Comment by germsvel** [comment]
👋 hi there! Thanks for the patience. The people who were maintaining Bamboo left thoughtbot. So I'm currently looking for a thoughtbot developer to take over maintenance of this project. If I can't find someone, I'll take over maintaining it. 

In the meantime, feel free to ping me if there's something urgent. Otherwise, I hope to start triaging Bamboo issues and PRs in the near future. I've been very busy, but I do want to make sure this library is well maintained. Hope that helps!

**Comment by dantswain** [comment]
@germsvel Thanks for the update!  Would you be willing to have non-thoughtbot help here?  I don't know how much we can commit, but my team recently started using bamboo for a big project and has interest in making sure it stays maintained.

**Comment by germsvel** [comment]
@dantswain help is always welcome! I think thoughtbot projects tend to have a thoughtbot maintainer, so that's why I would like to find one internally. But even then, I think the role of the maintainer is to provide guidance and direction so the library is a cohesive unit, but I don't think of the maintainer as the only one who commits code on the project.

**Comment by joshchernoff** [comment]
It can be very frustrating as a contributor if you don't think the maintainers are going to read your PRs and also when no one is addressing the correct way to contribute. An example: I added a small PR to address something very simple. Many other people also did the same after me, it would have been great to have someone address the redundant PR. But to make this worse the PR the was chosen didn't achieve the full effect as my pr did so it was also disregarded my initial efforts. All this to say I don't really care about my PR but it's not very much an incentive to keep trying to help. Which is all due to a lack of ownership.
