### ISSUE TITLE
After migrating from Phoenix 1.4 to 1.5 the render method started throwing errors

### ISSUE THREAD

**Issue by tmpduarte** [thoughtbot/bamboo#532]
We have a project running in Phoenix 1.4 and we migrated to 1.5. But as soon as we migrated we saw that the `render` method was throwing the following error:
```
** (Phoenix.Template.UndefinedError) Could not render "text_and_html_email.html" for XYZWeb.LayoutView, please define a matching clause for render/2 or define a template at "lib/xyz_web/templates/layout/**/*".
```

we were using the following code:
```
def invite_email(user) do

    new_email()
    |> to(user.email)
    |> from("xyz@xyz.com")
    |> subject("You have an invite to join xyz Apps")
    |> assign(:user, user)
    |> put_html_layout({XYZWeb.LayoutView, "organization/invite.html"})
    |> put_text_layout({XYZWeb.LayoutView, "organization/invite.text"})
    |> render(:text_and_html_email)
  end
```

and it worked until we migrated from 1.4 to 1.5. 
After digging further into the Bamboo library I found this method which was being called:
```
defp render_html_and_text_emails(email) do
    view_template = Atom.to_string(email.private.view_template)

    email
    |> Map.put(:html_body, render_html(email, view_template <> ".html"))
    |> Map.put(:text_body, render_text(email, view_template <> ".text"))
  end
```

This was forcing the use of a `text_and_html_email` template which was non existent. 
Before migrating the code was using the `organization/invite` template and was "ignoring" the atom passed. Similar to what the documentation suggests:
<img width="872" alt="Screenshot 2020-04-29 at 19 11 05" src="https://user-images.githubusercontent.com/1597565/80631144-384e6c80-8a4d-11ea-8d5b-6c5299f495cf.png">

I found a workaround which was to remote the `put_html_layout ` & `put_text_layout ` and call render with `|> render(:"organization/invite")`:

```
def invite_email(user) do

    new_email()
    |> to(user.email)
    |> from("xyz@xyz.com")
    |> subject("You have an invite to join xyz Apps")
    |> assign(:user, user)
    |> render(:"organization/invite")
  end
```

It works but I am not sure this is the right way to do it of if Bamboo needs to be updated as there have been changes to the rendering of templates in Phoenix 1.5. Or if it just requires a documentation update.

**Comment by joshchernoff** [comment]
1.5 has changed the way it deals with layouts, that said I'm not having the same issues as you and I use `put_html_layout` and even forgo using `put_text_layout` without issue.

```
  defp email(subject, recipient, url) do
    new_email()
    |> from({"Morphic.Pro", "no-reply@morphic.pro"})
    |> put_html_layout({EmailLayoutView, "email.html"})
    |> to(recipient)
    |> assign(:email, recipient)
    |> assign(:url, url)
    |> subject(subject)
  end
```

From the looks of it the error was telling you the problem. 
`** (Phoenix.Template.UndefinedError) Could not render "text_and_html_email.html" for XYZWeb.LayoutView, please define a matching clause for render/2 or define a template at "lib/xyz_web/templates/layout/**/*".
`

What you need to do is see why your current version of render is no longer pattern matching. 

When I run into this I just make a super greedy matching function and IO.inspect all the values being passed into see how they changed. I'd put my money on that you are patter matching in your render function that no longer matching because the view or template changed when you upgraded. If you added the `put_root_layout` in your router that could have done it. 

All that said I don't think this is an issue with Bamboo.

**Comment by tmpduarte** [comment]
@joshchernoff thank you very much for taking the time to look into this. 🙏 

I also don't know how this ever worked, I actually built a [simple demo using phoenix 1.5 and Bamboo](https://github.com/coletiv/elixir-bamboo-bug-reproduction) just to replicate the issue and to be able to share a full project containing an example.
I simply followed the readme from Bamboo and used the LocalAdapter to test. 

I think this is just a documentation issue. 
The documentation  states:
<img width="704" alt="Screenshot 2020-05-07 at 16 24 27" src="https://user-images.githubusercontent.com/1597565/81313038-402a9400-907f-11ea-8c1a-1d34e7055ec9.png">

If we do [that](https://github.com/coletiv/elixir-bamboo-bug-reproduction/blob/master/lib/bamboo_example/email.ex), Bamboo ignores that we passed the `email.text` & `email.html` layouts and tries to render `welcome.html` layouts. 

I took a look at the `Bamboo.Phoenix` code and tried to follow the 🐇. When calling render we have:

```
def render(email, template, assigns \\ []) do
# in our case template is :welcome
       Bamboo.Phoenix.render_email(@email_view_module, email, template, assigns)
end

def render_email(view, email, template, assigns) do
    email
    |> put_default_layouts
    |> merge_assigns(assigns)
    |> put_view(view)
    |> put_template(template)
    |> render
  end

defp put_template(email, view_template) do
    # the template that reaches here is :welcome, and it overrides the previously defined template (:email in our case)
    email |> put_private(:view_template, view_template)
  end
```

The `put_template` method overrides the view template which previously was `:email`. When the render actually happens phoenix tries to render a non-existing `welcome` template.


Maybe I am missing something but either the documentation should be improved or the code should change so that a `render` method that does not require a template atom to be passed, meaning our templates would not be overridden.

**Comment by maymillerricci** [comment]
@tmpduarte Thanks for the question and the sample app to reproduce! I think there's some confusion about where to put the email layout and template files. 

If you want to do:
```
  def welcome_email do
    new_email()
    |> put_text_layout({BambooExampleWeb.LayoutView, "email.text"})
    |> put_html_layout({BambooExampleWeb.LayoutView, "email.html"})
    # Pass atom to render html AND plain text templates
    |> render(:welcome)
  end
```
You'll want:
* *layout* files (that include `<%= @inner_content %>` to render the template if using Phoenix 1.5) called:
  * `lib/bamboo_example_web/templates/layout/email.html.eex` and 
  * `lib/bamboo_example_web/templates/layout/email.text.eex`, 
* *template* files called:
  * `lib/bamboo_example_web/templates/email/welcome.html.eex` and
  * `lib/bamboo_example_web/templates/email/welcome.text.eex`
* And you'll also need a `BambooExampleWeb.EmailView` if you're going to use templates in the `templates/email` folder, and use that in your `Email` module.

Take a careful look at https://hexdocs.pm/bamboo/Bamboo.Phoenix.html#module-html-layout-example and the location of the supporting template and view files, and hopefully that will help explain things more!

**Comment by joshchernoff** [comment]
@tmpduarte all of your issues are the result of your failure to understand the layout is the wrapper and the template is the email in question. 

Example: 

If I started a new app in phoenix and used the generator to scaffold up something "lets say a blog post"

We would see that we have a layout `app.html` found in our layouts folder and a template for our posts index page found in  `template/posts/index.html`

In this example the app is the wrapper for the index. Index is rendered as the result of `%= @inner_content %>`

Thus if we look at your example. Lets start with the first issue 
https://github.com/joshchernoff/elixir-bamboo-bug-reproduction/issues/1

We are calling
```
 |> render(:welcome)
```
https://github.com/coletiv/elixir-bamboo-bug-reproduction/blob/master/lib/bamboo_example/email.ex#L11 

But where is the email template? 
As you can see I address that here. 
https://github.com/joshchernoff/elixir-bamboo-bug-reproduction/commit/2a9bb54012cc4ded790787d6dc23033a0c2c0392

Now we got our welcome email defined, we now see we don't have correct layout specified. 
https://github.com/joshchernoff/elixir-bamboo-bug-reproduction/issues/2

thats because we are calling 
```
|> put_text_layout({BambooExampleWeb.LayoutView, "email.text"})
|> put_html_layout({BambooExampleWeb.LayoutView, "email.html"})
```
https://github.com/coletiv/elixir-bamboo-bug-reproduction/blob/master/lib/bamboo_example/email.ex#L8-L9

lets look how I fixed that. 
https://github.com/joshchernoff/elixir-bamboo-bug-reproduction/commit/3659d1c4cf6d9d09cce1a450a28991b426a45530

By moving our email layouts to the correct directory we address the issue of the layouts. 

Moving on from there we still have an issue because if we try to send an email we will see its missing the from.  https://github.com/joshchernoff/elixir-bamboo-bug-reproduction/issues/3

Lets fix that https://github.com/joshchernoff/elixir-bamboo-bug-reproduction/commit/e6a9add81ee7543d92396a30cdff73567280a1a8

Now that we got that, whats next?  Ah we are missing the `to` https://github.com/joshchernoff/elixir-bamboo-bug-reproduction/issues/4

Fix for that: https://github.com/joshchernoff/elixir-bamboo-bug-reproduction/commit/6f11272cf54cd5d0d5d4141ebd8cbfd44419809c

Next moving on to issue https://github.com/joshchernoff/elixir-bamboo-bug-reproduction/issues/5 We see our layout never did any thing to render the content of the view in question  so we fix that https://github.com/joshchernoff/elixir-bamboo-bug-reproduction/commit/ee7d69cf1a5f302059e8e3c425ed4d8bea277812 by adding `<%= @inner_content %> `

Now just for an extra nice step lets launch the show sent emails upon sending an email. 
https://github.com/joshchernoff/elixir-bamboo-bug-reproduction/commit/1d9bdbfd247a172a017b2a1f66b722c6744f3f88

And there we go everything is now working because the correct layouts are in their place, the correct email template is in its place and all the other requirements have been fulfilled and all I did was read the errors being reported and followed them.

**Comment by tmpduarte** [comment]
@maymillerricci & @joshchernoff thank you very much for all the time spent 🙏 
Indeed I didn't properly understand the layout mechanism.

The only thing I am missing is how did it work in the previous version of Elixir. That would require me to setup another example project with Phoenix < 1.5 😄 if I have time I will try to reproduce that!

Once again thank you 🙏
