### ISSUE TITLE
EEx rendering pipeline

### ISSUE THREAD

**Issue by lleger** [thoughtbot/bamboo#541]
I have an umbrella app. The context app where the domain logic lives sends emails and the Phoenix app calls into the contexts and as a side effect sometimes emails are sent. 

Using Bamboo with `Bamboo.Phoenix` violates the app boundary, since it requires the templates to be in the Phoenix app, but the mailer logic in the context app. It also means the context app has an unnecessary dependency on Phoenix. It can also create circular dependencies. 

All of this works but it’s a bit of an anti-pattern, so I set out to fix it. I did this by writing an EEx rendering pipeline. I modeled the API off `Bamboo.Phoenix` so it was a one-line diff to switch over. The only difference is you don’t have access to any of the Phoenix view helpers, but that didn’t cause any issues for me. 

I’m wondering if the maintainers would see value in this being a part of Bamboo itself. If so I would be happy to open a PR for it! But I wanted to check before I did the work to do so, because I believe there may be some refactoring involved (e.g. the similar `assign` API can be hoisted and included in both `Bamboo.Phoenix` and a theoretical `Bamboo.EEx` instead of reimplementing the same code).

**Comment by germsvel** [comment]
Hi @lleger, thanks so much for opening this issue! 

I've been trying to think about this for a little while, though I don't have a clear idea on whether or not this would be good to include in Bamboo. But I didn't want to leave this without a comment, because I have looked at it, and I'm thinking about it. 

I definitely get the desire to separate the email templates from the web layer that Phoenix provides. Currently, Phoenix [is not required](https://github.com/thoughtbot/bamboo/#using-phoenix-views-and-layouts) to use Bamboo, but I realize it provides a lot of niceties to generate html. So I imagine a lot of people feel like they have to depend on Phoenix. 

I do have a few questions: 

> All of this works but it’s a bit of an anti-pattern, so I set out to fix it. I did this by writing an EEx rendering pipeline. 

Is that EEx pipeline something we could see to get a better sense of what we're talking about?

> The only difference is you don’t have access to any of the Phoenix view helpers

Which helpers do you mean by that? You mean there wouldn't be any equivalents to `render` or route helpers, etc.? 

My last thought is, could this be a separate library to which we could point people if they don't want to depend on Phoenix? And are there any other EEX rendering libraries out there that already do something like this? 

Thanks again!

**Comment by lleger** [comment]
Hi @germsvel! Sorry for the delayed response, you commented just about an hour before my daughter was born, so I'm just now seeing this!

> Is that EEx pipeline something we could see to get a better sense of what we're talking about?

The rendering portion is honestly pretty simple. It just uses [`EEx.function_from_file/5`](https://hexdocs.pm/eex/EEx.html#function_from_file/5). Then you can do something like `use Bamboo.EEx, root: "lib/my_app/email`. The `root` option here specifies the path to the templates; it just compiles all the templates in the given directory. The current version is < 100 LOC, but is missing some of the helpers defined in `Bamboo.Phoenix` (which can easily be added).

I'll paste some code at the end for you to see.

> Which helpers do you mean by that? You mean there wouldn't be any equivalents to `render` or route helpers, etc.?

Correct, you don't have the Route helpers or anything from e.g. `Phoenix.HTML` (which, you could include if you wanted; that doesn't cause the circular dependency issue).

The other helpers that are provided in `Bamboo.Phoenix` like `render`, `assign`, etc were all implemented so the API for `Bamboo.EEx` and `Bamboo.Phoenix` are 1:1.

> My last thought is, could this be a separate library to which we could point people if they don't want to depend on Phoenix? And are there any other EEX rendering libraries out there that already do something like this?

It certainly could be an external library, but IMO it shouldn't be. As long as Bamboo includes an integration with Phoenix, it should include a way to render templates without using Phoenix. It's not a lot of code, but it's boilerplate that shouldn't have to be rewritten. The current use case of Bamboo rendering without Phoenix is untenable, in my view, which is why I wrote this.

> And are there any other EEX rendering libraries out there that already do something like this?

I mean, EEx is included in Elixir and is used by lots of libraries. The word "pipeline" I used is just window-dressing: all the module is doing is using a bit of file directory looping and native EEx functions inside a `__using__` macro. And actually, Phoenix's views are just using EEx under the hood, so really `Bamboo.EEx` and `Bamboo.Phoenix` do the same thing, just the former has fewer steps.

***

Here is the relevant code for rendering the views, the rest of the module is just implementing the same helpers from `Bamboo.Phoenix` and most of those implementations are identical.

```elixir
  defmacro __using__(root: root) do
    quote do
      require EEx

      import MyApp.Bamboo.EEx

      @template_dir unquote(root)
      @email_module __MODULE__

      @template_dir
      |> File.ls!()
      |> Enum.each(fn file ->
        [filename, type, _ext] = String.split(file, ".")

        function_name =
          ("render_" <> filename <> "_" <> type)
          |> String.to_atom()

        EEx.function_from_file(
          :def,
          function_name,
          Path.join(@template_dir, file),
          [:assigns]
        )
      end)

      def render(email, template) do
        MyApp.Bamboo.EEx.render_email(@email_module, email, template)
      end
    end
  end
```

**Comment by germsvel** [comment]
@lleger congrats on the birth of your daughter! 🎉 🎊 🥳

I've been thinking about this issue, and I definitely see why it makes sense that Bamboo would have a way to render views without having to depend on Phoenix. I also learned that this has been requested before in https://github.com/thoughtbot/bamboo/issues/323. So I'm on board with introducing some view/eex rendering layer to Bamboo. 

Thank you for posting that sample code! It looks good. I'm vaguely familiar with how EEx turns templates into functions, but it's been a while since I've looked into the docs. 

One thing I'd like to try to figure out is what would make a good first view/eex rendering layer that we could ship, and what other things we could bring on as additions. In other words, what should we include in a first PR? Should we aim for feature parity with what users can currently do with `Bamboo.Phoenix`? Not sure if feature parity is easy or not. It might be easier to introduce it in several PRs, but I don't know. You might have a better sense.  What are your thoughts?

**Comment by lleger** [comment]
@germsvel Thank you so much!

> One thing I'd like to try to figure out is what would make a good first view/eex rendering layer that we could ship, and what other things we could bring on as additions. In other words, what should we include in a first PR? Should we aim for feature parity with what users can currently do with `Bamboo.Phoenix`? Not sure if feature parity is easy or not. It might be easier to introduce it in several PRs, but I don't know. You might have a better sense. What are your thoughts?

IMO we should ship with feature parity since it's very easy to get there. My first pass implementation was 85% parity, but because that's all I needed, not because there were technical hurdles.

The guiding principle I tried to follow was to get it to a 1-line diff. I.e., complete API cohesion. I was able to do it such that the diff looked like:

```diff
 defmodule MyApp.Email do
-  use Bamboo.Phoenix, view: MyAppWeb.EmailView
+  use Bamboo.EEx, root: "lib/my_app/email
```

To get there, a lot of functions that are in `Bamboo.Phoenix` will need to be abstracted. The implementation for EEx and Phoenix for most of those functions is 1:1 (e.g. the `assigns/3` function, since it's on the struct itself and has nothing to do with the Phoenix rendering itself). But I don't think that's a major issue. 

Perhaps we can move those into a `Bamboo.Template` module?

I'm happy to begin a PR, I think I'll have some time to work on it in the near-term.

**Comment by germsvel** [comment]
@lleger 

> IMO we should ship with feature parity since it's very easy to get there. 

That sounds excellent! 🥳

I like the guiding principle you had in mind &mdash; making it a one line change for users. It makes sense that Bamboo.Phoenix functions will have to be abstracted. What do you think about a `Bamboo.View` module instead of `Bamboo.Template`? That remains familiar to users who use Phoenix, yet at the same time it's not confused with the actual HTML templates.

**Comment by lleger** [comment]
@germsvel `Bamboo.View` sounds good to me!

**Comment by germsvel** [comment]
@lleger I had a bit of time over the holidays and added a PR for adding `Bamboo.Template` and `Bamboo.View`. I'd love to hear your thoughts on it, especially since it ended up deviating from your original implementation. https://github.com/thoughtbot/bamboo/pull/576

**Comment by LostKobrakai** [comment]
I'm not sure if you're aware, but phoenix recently extracted their view layer into a separate project, so that e.g. email libraries can depend on it without pulling in the whole framework: https://github.com/phoenixframework/phoenix_view

**Comment by lleger** [comment]
Hey @germsvel! Sorry for the radio silence, been busy with kiddos. But yeah I had stubbed something out then realized, as @LostKobrakai mentions, that Phoenix View was going to be pulled out, so I scrapped that whole branch and meant to drop a note here about it. I think using Phoenix View resolves this in my mind. It's a best-in-class implementation of an HTML pipeline using EEx, so it should be a good way for anyone to do what I laid out in my initial comment.

**Comment by germsvel** [comment]
Thanks @lleger and @LostKobrakai. 

Yeah, someone mentioned that to me in the Elixir slack the other day, and I made a note about it in the PR. https://github.com/thoughtbot/bamboo/pull/576#issuecomment-760991819

I wonder if the code would be helpful to anyone anymore (maybe not wanting to bring in phoenix view as a dependency), but I'm guessing it makes more sense to close the PR.
