### ISSUE TITLE
Default base URI for SendGrid doesn't match SendGrid docs

### ISSUE THREAD

**Issue by camelpunch** [thoughtbot/bamboo#544]
I'm running a strict environment in Istio where all outbound traffic must be allowed explicitly. I had to read the source code of Bamboo to confirm it was using sendgrid.com and not api.sendgrid.com.

Although the former works, I imagine that SendGrid would want the flexibility to turn this off one day, and perhaps we should be using api.sendgrid.com instead?

See e.g. https://sendgrid.com/docs/for-developers/sending-email/api-getting-started/

**Comment by germsvel** [comment]
Thanks for opening this issues @camelpunch! It seems like that was changed when we adopted v3 of the api in [this commit](e8e981652998ac1af99b606d66acf10d848fca3d). But you're totally correct in that it seems we should be using the https://api.sendgrid.com/v3/ instead of what we're doing now. 

I'd like to make sure that changing that url won't cause any breakages, but I can't imagine it doing so. Still, I'll do some due diligence and open a PR, unless someone else is willing to do that!
