### ISSUE TITLE
Mailgun not recognising CSS, images and fonts

### ISSUE THREAD

**Issue by ivan-rivera** [thoughtbot/bamboo#615]
I'm using Bamboo + Mailgun to send HTML emails. It works when I use the LocalAdapter, but when it goes through the Mailgun service, all styles are ignored. It appears that Mailgun just doesn't know where to find my images and styles. I strongly suspect that this is a Bamboo issue. You can find my template together with the relevant setup [here](https://github.com/ivan-rivera/sleep_rescue_api/blob/master/lib/sleep_rescue/mail/templates/layout/email.html.eex). I've also created a thread about this on the [Elixir Forum](https://elixirforum.com/t/bamboo-mailgun-not-using-css/41126).

**Comment by germsvel** [comment]
Thanks for opening this issue @ivan-rivera.

This is a very difficult issue to debug without having some way to reproduce the error. Could you try to create a simple app that has that error and so that I could reproduce it with Mailgun? 

In the meantime, I've taken a look at the template you linked to and the Elixir Forum post. What someone posted on the forum is true: CSS in emails is tough. Many people put the CSS inline. For URLS, you need to use absolute urls, not relative paths. For example, in Phoenix you would want to use `_url` helpers instead of `_path` helpers.

**Comment by ivan-rivera** [comment]
@germsvel thank you for responding! After learning a little more about this, I think we should close this issue. I still haven't had the chance to try the inline CSS solution, but it should be the way to go and Bamboo should not be blamed for this. Thank you again for looking into it.
